baseurl = "https://robzwitserlood.s3.nl-ams.scw.cloud"
DefaultContentLanguage = "en"
title = "Home"
# Using theme as git submodule
theme = "beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[deployment]
  [deployment.targets]
    - name: "production"
      URL: "https://robzwitserlood.s3.nl-ams.scw.cloud"

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"

[Params]
  homeTitle = "Welcome!"
  subtitle = "Personal website of Rob Zwitserlood"
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  cusdisID = "XXX" # Get your App id from cusdis.com
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Params.author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Rob Zwitserlood"
  website = "robzwitserlood.nl"
  email = "robzwitserlood@tuta.io"
  github = "robzwitserlood"
  linkedin = "robzwitserlood"
  medium = "robzwitserlood"
  strava = "userid"

[[menu.main]]
    name = "CV"
    url = "page/cv/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 2

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

#[[menu.main]]
#    name = "Tags"
#    url = "page/tags/"
#    weight = 4
